title: Universal Bits
short_title: U Bits

about:
  long: >- # ignore line-breaks until next key.
    Sometimes, I'll find knowledge that has stood the test of time and applies
    across disciplines. It helps me connect the dots, make better decisions, or
    simply understand things more deeply. Some call it "mental models"; I like
    to call it "Universal Bits" and I write about it here. You will also find me 
    writing about computer science and any topic that captures my curiosity.
  short: >-
    Hi! 👋 Exploring mental models, connecting the dots, and writing about it.

# --- Required by Jekyll SEO

twitter:
  username: AdrianoDiLuzio
  card: summary

tagline: aldur's blog

description: >-
  Exploring mental models, connecting the dots, and writing about it.

logo: /assets/images/favicon.svg

social:
  name: aldur
  links:
    - https://x.com/AdrianoDiLuzio
    - https://github.com/aldur

# --- /Required by Jekyll SEO

# Author for both site and posts
author:
  name: aldur
  nick: aldur
  email: hello@aldur.blog
  pgp_pk_url: https://github.com/aldur.gpg
  twitter: AdrianoDiLuzio

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  # This requires `url` being set.
  # Also, its effect depend on _where_ you position in in the plugins list.
  # See: https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap

# Theme-specific settings

minima:
  skin: auto

  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/
  # if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  social_links:
    - title: aldur on GitHub
      icon: github
      url: "https://github.com/aldur"
    - title: AdrianoDiLuzio on X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/AdrianoDiLuzio"

  show_excerpts: true
  show_tags: true

# If you want to link only specific pages in your header, uncomment this and
# add the path to the pages in
# order as they should show up.
#
header_pages:
  - micro.md
  - about.md

strict_front_matter : true

liquid:
  strict_filters    : true

incremental         : false

exclude:
  - LICENSE
  - README.md
  - flake.*
  - flake.nix
  - gemset.nix
  - .direnv/

defaults:
  # When not specified, posts will have a `post` layout
  # and have `articles` in the categories.
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories:
        - "articles"
  # Same for `micros`
  -
    scope:
      path: ""
      type: "micros"
    values:
      layout: "post"
      is_micro: true
      show_excerpt: false  # Ensure no excerpts in tag pages
      categories:
        - "micros"

collections:
  micros:
    output: true
    permalink: micros/:year/:month/:day/:title:output_ext
    show_excerpts: false

redirect_from:
  json: false

feed:
  collections:
    - micros

# Silence Saas deprecation warnings, to be removed after this is fixed upstream in minima:
# https://github.com/jekyll/minima/issues/815#issuecomment-2440028795
sass:
  quiet_deps: true
  silence_deprecations: ['import']
