title: Universal Bits
short_title: U Bits

about:
  long: >- # ignore line-breaks until next key.
    I sometime _stumble_ on fundamental insights of knowledge that stood the test
    of time, apply across different disciplines, and help me connect the dots,
    make better decisions, or simply _understand_ things. Some like to call them
    "mental models", I call them "Universal Bits". Whenever that happens, I write
    about it here. I also write about computer science and all other topics that
    fascinate me.
  short: >-
    Hi! 👋 Computer scientist exploring mental models, connecting the dots, and
    writing about it.

# --- Required by Jekyll SEO

twitter:
  username: AdrianoDiLuzio
  card: summary

tagline: aldur's blog

description: >-
  Exploring mental models, connecting the dots, and writing about it.

logo: /assets/images/favicon.svg

social:
  name: aldur
  links:
    - https://x.com/AdrianoDiLuzio
    - https://github.com/aldur

# --- /Required by Jekyll SEO

# Author for both site and posts
author:
  name: aldur
  nick: aldur
  email: hello@aldur.blog
  pgp_pk_url: https://github.com/aldur.gpg
  twitter: AdrianoDiLuzio

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # This requires `url` being set.
  # Also, its effect depend on _where_ you position in in the plugins list.
  # See: https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap

# Theme-specific settings

minima:
  skin: auto

  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/
  # if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  social_links:
    - { platform: github, user_url: "https://github.com/aldur" }
    - { platform: x, user_url: "https://x.com/AdrianoDiLuzio" }
    #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
    #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and
# add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

show_excerpts: true
show_tags: false

strict_front_matter : true

liquid:
  strict_filters    : true

incremental         : false

permalink: pretty

exclude:
  - LICENSE
  - README.md
  - flake.lock
  - flake.nix
  - gemset.nix
