title: Universal Bits

description: >- # ignore line-breaks until next key.
  aldur's blog

author: false

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      author:
        # Default author, unless differently specified.
        - Adriano Di Luzio

# Theme-specific settings

minima:
  skin: auto

  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/
  # if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  social_links:
    - { platform: email, user_url: "mailto:firstname_lastname@gmail.com" }
    - { platform: github, user_url: "https://github.com/aldur" }
    - { platform: x, user_url: "https://x.com/AdrianoDiLuzio" }
    #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
    #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and
# add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

show_excerpts: true
show_tags: false
